### ISSUE TITLE
Feature Tracker

### ISSUE THREAD

**Issue by benjaminpope** [benjaminpope/drpangloss#2]
Here are some features we need to implement: 

## Basic Features
- [ ] Visibility functions for rings, gaussians
- [ ] Model evidences by Laplace
- [ ] Monte Carlo injection-recovery
- [ ] ROC Curves from evidence / injection recovery
- [ ] Automatic plotting functions
- [ ] Interface to MCMC libraries (eg BlackJax, NumPyro)

## API Features
- [ ] Unify APIs of all likelihood functions (eg what is a contrast?)
- [ ] Model specification by equinox object
- [ ] Interface with dLux
- [ ] Interface with Harmonix
- [ ] Fix spaghetti code calling implaneia for IO, simplify dependencies

## Unit Tests
- [ ] Unit tests for gridding
- [ ] Unit tests for plotting

## Docs
- [ ] Document all visibility functions
- [ ] Document all likelihood functions
- [ ] Document data IO
- [ ] Document plotting functions

## Examples 
- [ ] Comparison of contrast detection limits with Absil, Ruffio, UQ methods
- [ ] Contrast curve for non-binary source
- [ ] MCMC fitting example
- [ ] Fix data directory to have something attractive + public there for examples and unit tests

**Comment by benjaminpope** [comment]
`vmap` syntax, object-oriented model specification, automatic plotting code, unit tests, and unification of likelihoods to use flux (not contrast) completed in PR #11.
